server:
  port: 8888
  servlet:
    context-path: /springboot

spring:
#  profiles:
#      active: dev
  datasource:
    #初始化数据结构/数据
    schema: classpath:h2/schema.sql
    data: classpath:h2/test-data.sql
#    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    platform: h2
#    username: sa
#    password:
#    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#      settings:
#        trace: false
#        web-allow-others: false
#  mvc:
#    static-path-pattern: /static/**
#  resources:
#    #静态资源位置
#    static-locations: classpath:/static/

  thymeleaf:
    #开发配置为false,避免修改模板还要重启服务器
    cache: false
    #prefix: /WEB-INF/templates/
  mvc:
    favicon:
      enabled: false
#  redis:
#    database: 5
#    host: ${REDIS_HOST:localhost}
#    port: ${REDIS_PORT:6379}
#    password: ${REDIS_PASSWORD:}

logging:
  level:
    com.xxx: debug

task:
  pool:
    corePoolSize: 20
    maxPoolSize: 40
    keepAliveSeconds: 300
    queueCapacity: 50